name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install pytest requests
      - name: Run Python tests
        run: pytest -q ai/tests/test_jarvis.py
      - name: Build kernel (no ISO)
        run: |
          sudo apt-get update
          sudo apt-get install -y make gcc-multilib
          ./scripts/build.sh || true
